WIP feat(Consents): Terms should be editable from Django admin view.
carpentries/amy pull request #1840
Opened 2021-03-12 17:05 UTC by lauryndbrown

Fixes https://github.com/carpentries/amy/issues/1831.

2021-03-12 17:52 UTC, lauryndbrown commented
Current state:
<img width="635" alt="Screen Shot 2021-03-12 at 9 51 20 AM" src="https://user-images.githubusercontent.com/12959365/110978767-a1169e80-8318-11eb-9f56-644e4224d0db.png">
<img width="1363" alt="Screen Shot 2021-03-12 at 9 51 28 AM" src="https://user-images.githubusercontent.com/12959365/110978773-a4aa2580-8318-11eb-8766-982920c95cc0.png">
<img width="1370" alt="Screen Shot 2021-03-12 at 9 51 44 AM" src="https://user-images.githubusercontent.com/12959365/110978782-a7a51600-8318-11eb-9e6c-fead0242f5cf.png">

2021-03-14 19:42 UTC, lauryndbrown commented
<img width="1384" alt="Screen Shot 2021-03-14 at 12 41 36 PM" src="https://user-images.githubusercontent.com/12959365/111081895-b3344080-84c2-11eb-88c9-a11f8644c848.png">

2021-03-14 21:25 UTC, pbanaszkiewicz requested changes
Looks good! Can you introduce the `blank` option to migration `0001` instead of creating a new migration?

2021-03-14 21:25 UTC, pbanaszkiewicz commented on amy/consents/migrations/0002_auto_20210314_1928.py
> +# Generated by Django 2.2.17 on 2021-03-14 19:28
Please introduce the changes to `0001` migration.

2021-03-20 16:00 UTC, lauryndbrown commented
@pbanaszkiewicz could you take another look?

2021-03-21 21:19 UTC, pbanaszkiewicz approved these changes
Looks good, thanks for the changes.

2021-03-22 04:28 UTC, merged