check for null values when loading custom keys
carpentries/amy pull request #2339
Opened 2023-02-10 14:55 UTC by elichad

Fixes #2336 .

I wrote some tests, but do we actually use custom keys at all?

2023-02-10 16:06 UTC, pbanaszkiewicz commented
Custom keys have been introduced quite recently. I think the original idea was to customize some community roles with them, e.g. when a role was related to a specific lesson we could add "lesson url" custom key and fill it out when assigning the role.

2023-02-10 16:13 UTC, pbanaszkiewicz requested changes

2023-02-10 16:13 UTC, pbanaszkiewicz commented on amy/communityroles/fields.py
> +            value_deserialized_dict = {}
`json.loads` can potentially return other types that will fail to dict transformation, for example:

```python
>>> S = '["asd", "dsa", "zxc"]'
>>> json.loads(S)
['asd', 'dsa', 'zxc']
>>> dict(json.loads(S))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: dictionary update sequence element #0 has length 3; 2 is required
```

I'm wondering if `try-except` wouldn't be better here. You can add logging of the failed value, too, so in any case we could diagnose faster.

2023-02-10 16:13 UTC, pbanaszkiewicz commented on amy/communityroles/tests/test_fields.py
> +        self.assertEqual(context["widget"]["subwidgets"], [])
Can you follow Arrange-Act-Assert pattern? https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/

I usually separate each section within a test with comments like so:

```python
def test():
  # Arrange
  widget = Widget()

  # Act
  widget.click()

  # Assert
  assert widget.focused is True
```

2023-02-15 09:53 UTC, elichad commented
@pbanaszkiewicz this one is the hotfix that I mentioned yesterday

2023-02-15 17:34 UTC, pbanaszkiewicz approved these changes

2023-02-15 17:34 UTC, pbanaszkiewicz commented
Looks good to me!

2023-02-17 11:50 UTC, merged